"""add nudge_comment_language + nudge_use_ai to org_workflow_settings

Two new per-tenant nudge knobs:
  * nudge_comment_language: which language AGENA's auto-comment uses
    (en / tr / de / es / it / ja / zh). Defaults to 'en'.
  * nudge_use_ai: when true, the body is generated by the org's
    reviewer agent (claude_cli/codex_cli/openai/gemini) so it picks up
    the actual recent activity and writes a contextual ping. When
    false (default), we fall back to the static template.

Revision ID: 0044_nudge_comment_lang
Revises: 0043_organization_modules_unique
Create Date: 2026-05-02
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0044_nudge_comment_lang'
down_revision = '0043_organization_modules_unique'
branch_labels = None
depends_on = None


def _column_exists(bind, table: str, column: str) -> bool:
    inspector = sa.inspect(bind)
    if table not in inspector.get_table_names():
        return False
    return any(c['name'] == column for c in inspector.get_columns(table))


def upgrade() -> None:
    bind = op.get_bind()
    if not _column_exists(bind, 'org_workflow_settings', 'nudge_comment_language'):
        op.add_column(
            'org_workflow_settings',
            sa.Column(
                'nudge_comment_language',
                sa.String(length=8),
                nullable=False,
                server_default='en',
            ),
        )
    if not _column_exists(bind, 'org_workflow_settings', 'nudge_use_ai'):
        op.add_column(
            'org_workflow_settings',
            sa.Column(
                'nudge_use_ai',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            ),
        )


def downgrade() -> None:
    bind = op.get_bind()
    if _column_exists(bind, 'org_workflow_settings', 'nudge_use_ai'):
        op.drop_column('org_workflow_settings', 'nudge_use_ai')
    if _column_exists(bind, 'org_workflow_settings', 'nudge_comment_language'):
        op.drop_column('org_workflow_settings', 'nudge_comment_language')
